[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://meetingmind-backend.onrender.com"
  VITE_AI_SERVICE_URL = "https://meetingmind-ai.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://meetingmind-backend.onrender.com"
  VITE_AI_SERVICE_URL = "https://meetingmind-ai.onrender.com"
