version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: meetingmind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://meetingmind:password123@postgres:5432/meetingmind
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - AI_SERVICE_URL=http://ai-service:8000
      - CORS_ORIGINS=http://localhost:3001,http://localhost:3000,http://localhost:5173
      - SLACK_CLIENT_ID=demo-slack-client-id
      - SLACK_CLIENT_SECRET=demo-slack-client-secret
      - GOOGLE_CLIENT_ID=demo-google-client-id
      - GOOGLE_CLIENT_SECRET=demo-google-client-secret
      - EMAIL_USER=demo@example.com
      - EMAIL_PASS=demo-password
      - NOTION_CLIENT_ID=demo-notion-client-id
      - NOTION_CLIENT_SECRET=demo-notion-client-secret
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/meetingmind
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./ai-service:/app
      - ai_models:/app/models
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_WS_URL: ws://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
  ai_models:
